- README.md
Changes made to the "Languages and Techniques" section in the README.md file.
> #10-Describe-Front-End-Languages-Techniques

- README.md
Describing the objectives of the project.
> Modified README.md to include the objective 

- README.md
Add name "Antonio Crispino" and username "antonio-crispino" under the "Team Members" section in the README.md file.
> #16-Add-Team-Member-Name-Antonio

- README.md
Added my name and GitHub username to the README.md
> Update READEME.md with Name - Justin

- README.md
Added the enumeration of the frameworks and database used the backend Languages and Technology section of the README
> adding the Back-End Lang and Tech to READEME.md #9

- README.md
> adding my name to README.md (Bozhidar)

- README.md
Plus changed I bit the text of the objective to be more substantial.
> Reformatted the structure and font of README.md

- README.md
Increased the difference in header size for our main title and the sub titles
Closes #35
> Changed header sizes to have title stand out more

- front-end/src/components/Photo/Photo.css
- front-end/src/components/Photo/Photo.jsx
added heart icon, fixed up photo header to  contain variables
> #71-implemented-photo-footer

- front-end/src/components/Forms/RegistrationForm.jsx
implemented registration form, just needs to be opened on sign in page
> #72-implemented-registration-form

- api/app.js
- api/data_access_layer/usersDAO.js
- api/routes/usersController.js
- api/views/register.jade
Moddified registration controller to support username and password and modified to file name to comply with appropriate syntax.
> #60 - Moddified registration controller to support username and password

- api/app.js
- api/data_access_layer/picsDAO.js
- api/routes/PicsController.js
- api/service_layer/PicsService.js
Errors are not yet handled but it is working.
> #26-Added-comment-posting-to-a-picture

- api/app.js
- api/package-lock.json
- api/package.json
- api/routes/dashboard.js
- api/routes/login.js
- api/routes/logout.js
- api/views/login.jade
Will need to "npm install --save express-session" to add the node modules on your local end.
> Added login with session, dashboard to verify, and logout

- front-end/src/components/Photo/Comments.css
- front-end/src/components/Photo/Comments.jsx
- front-end/src/components/Photo/Photo.jsx
added photo comments, not finalized, still need to print out comments when they are typed
> #93-added-photo-comments

- api/app.js
- api/routes/dashboard.js
- api/routes/login.js
- api/routes/profile.js
- api/views/profile.jade
- front-end/src/App.jsx
- front-end/src/components/Login/Login.jsx
Modified backend to accept credentials.
Modified front end to send credentials.
Modified /profile route to send the entire user.
> fixed frontend and backend session communication

- api/app.js
- api/data_access_layer/followDAO.js
- api/routes/follow.js
- api/routes/profile.js
- api/service_layer/followService.js
- api/views/follow.jade
Added route for /follow/:username
Added DAO for following
Added function that adds username into the array of users which the current session user is following
> Implemented Follow for Backend

- api/data_access_layer/picsDAO.js
- api/routes/PicsController.js
- api/service_layer/PicsService.js
Now the description to posting a picture is not mandatory and, as intended, the expected field is 
picture: the picture 
description: "the description" 
in a form-data format
> Changed the pic description for picture posting

- api/app.js
- api/routes/following.js
- api/service_layer/followService.js
Added /following/:username
Will display all the information related to that username in the followDAO
> added backend method for displaying followed users

- api/package.json
- api/routes/usersController.js
- api/service_layer/RegistrationService.js
- api/test/test.js
- package-lock.json
Created unit tests for:
- Registration
- Login
- Following
It Will be implemented in CI pipeline.
> Created unit tests for CI #106

- front-end/src/components/Photo/Comments.css
- front-end/src/components/Photo/Comments.jsx
- front-end/src/components/PhotoGallery/PhotoGallery.jsx
comment section improved, adds listgroup items on button click, needs backend implementation
> #112-comments-section-improved

- front-end/src/App.jsx
- front-end/src/components/Login/Login.jsx
- front-end/src/components/Navigation/Navigation.jsx
- front-end/src/components/PhotoGallery/PhotoGallery.jsx
- front-end/src/components/Registration/Registration.jsx
- Connected user session on front-end
- Enabled logout of user session
> #114-Connect-User-Session-and-Logout

- front-end/src/components/Photo/Comments.css
- front-end/src/components/Photo/Comments.jsx
- front-end/src/components/Photo/Photo.css
Improved styling for the photo comments
> #112-improved-comments-css

- front-end/src/components/Photo/Comments.jsx
- front-end/src/components/Photo/Photo.jsx
- front-end/src/components/PhotoGallery/PhotoGallery.jsx
comment info sent, now must be retrieved and displayed for each image
> #112-sent-comment-info-to-be

- front-end/src/components/Photo/Comments.jsx
- front-end/src/components/Photo/Photo.jsx
- front-end/src/components/PhotoGallery/PhotoGallery.jsx
retrieved comment data from the backend
> #112-retrieved-comment-info

- api/app.js
- api/data_access_layer/followDAO.js
- api/routes/unfollow.js
- api/service_layer/followService.js
- api/views/unfollow.jade
> Added unfollow, added followers, fixed follow

- api/data_access_layer/picsDAO.js
- api/routes/PicsController.js
- api/service_layer/PicsService.js
Tested the functionalities on my end using Postman.
> #145-Posting/Getting-Profile-Pic

- api/routes/PicsController.js
- api/service_layer/PicsService.js
> added-deleting-pic-feature
